language: java

jdk:
- oraclejdk8

env:
  global:
  
    - # ^^ OSSRH_JIRA_USERNAME
    - # ^^ OSSRH_JIRA_PASSWORD
    - # ^^ GPG_KEY_NAME
    - secure: TWycCGAWvL45h2YN6I0KEXP5fYFCv65UTEft34bDh2YZqACa0UrndKGexNl0+33v+7ldZdm+MXqMLal3yql9PPuSO5QnjIcL+qwptk679+xYm4t5susHim2G1bBXj6SM9LGLsgk/P5x0y0VA8SO2rioy4cvrzQXWBvioD+e2G4s/nNMZQAI+PH5geQvchsNylFFhDVD4bqoASjtnQMz/NMK0hPA0ecsB8wGLvQWOSho/Med9ZqaqEL+ConoXAkLiRIlIRbtaYKRGPACYWNmSLp1+64PT57Gs2Y/YMT/Id+reqmPm8zav4Q3l1sjPYloP9R3ZgX2fK9X4M9ONa8RJejSc4tj0QfCCg5PWnLy1HUcAzIqMKo0V2+wqmmMCOZf8zxQtjUvvfY15Qz5l+RQrYHBuhaF2o9i9+eGoQ6dCsGSJAFE9fx94AicWs/xFulYvMDWbhMYE85ss5pxrs5QMiUWiZ2NiYCCMjJlEcFWq0FS8JWc9vIUIAgQSyIgiHVV6pCVrxwUpo+MLvOtyudPYsV0agEZpkltM9at4NHRFlXWW2cdLOtqnaSHGP+3ylWk3lMZgdp4WgNMixgCEee7WsvkPcyiEnQGM2jQ1OdZ1+ZFv+HrNeiwscobblvLCIQCgm6NUxeuuCMaaopVfOztrLdW7Gmwv89UrYfY40lFQ/5M=
    - # ^^ GPG_PASSPHRASE
    - secure: J5ql4cChNVE8usEvALUpZf1SObMZbyZwhXCoU9dXqsdhy0XdwuKuQZcNuasKzoERF5cbWTPVNQrbQaBXceTi6lQKOIWEPeYLaxk7ON7eKVkNMERX03mbB86+Pre1Ci8f9p6yd427+auzSK8FjPi37MtE8lAFj34/PQPn0lSXWyxAyj3XxHTohVt/ExK/NrQLLIOZr1Y8MMesdb9rBkS+LClSx5av05uJnI+hWzk38B23QUY10K7zstUpDDkzngo4Cl0lBjt1lNwGnZsbkqZS1dG50tyGWCnsML8iIaRCc2acw41DrX4JE8PZl303G4KIei7O8mD64xJCjZvqrSBL861rkmfiHFwoqWrCFgmwf3YfO52+GheBWAdoEr4eJ0bS92oXr397THrHHXvxgjMlxi5j6OWMK8K807klSOAFNy4MM3mwagkJtIwhVYnrawmMZxolimNtMciUypB5SYv7YBr1lY9CWB6SMyQu1JO4Q8RjK+UJ94SzOUNzFkTmW6NGZvbKw32Y7PvUgSArdLadyUbsX50N3/KluWsSqVpC/g/ReXhmoy4KXPan19eHfhXOgWQpanP3ienofdlKjGaC+wxzLjeUljXmS2hDCv/aw6ha64KmEgGoQ55ly20aEEGH9KXHflBDAlYAnotx8YeodgdmLQ3fHgi4O4IsTVfcy+0=

install:
  - cd chao
  - pwd
  - if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then openssl aes-256-cbc -K $encrypted_e12cfdc024de_key -iv $encrypted_e12cfdc024de_iv -in codesigning.asc.enc -out signingkey.asc -d; gpg --fast-import signingkey.asc;  mvn deploy -P release --settings mvnsettings.xml; else mvn install -P !release -Dmaven.javadoc.skip=true -B -V; fi

cache:
  directories:
    - ~/.m2/repository
