language: java

jdk:
- oraclejdk8

env:
  global:
  
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: NubQgarYbRHaBXBdXR0tk4ASjtcmQMzAFcmBTe9DMGa+aEhCiI6RKW20Mp+szPAanmHbDXIRLMVwFTkeDuCRKifhWYf+ql17vnPClhQduVYevik7xpYNij2OdcoKTAFtJZrEwCAxnH++23fkE0nyqa2j4+PoGW9QG8ryZ4o4KBnN7VFHiL2tYepvYXT+o0aEYyfL7djoCKpHPEo2p8xpfKhyPhMd0BDFXu8dEt8O2pPQNJqsUHJFlFG6Ur7uU9xvq9+EZQGxGQM31dG07ORWIrBdAl6CjhjGg3Igeawvnb/LbR6qpAKhLAFIwcB0LHZD008dIT+OGk7OcuXqoskGYnZA0zMHeh8RSnOS/VuTVei+DIexzmJECmFhdfSwElP2x9PEaiG5/w/v2TJmdSVItKe5SMf2wEH2+M/p0ls87Sewqu+DhBG1ZxRvP/1i/+W2GUWeD4q59xle9sMLtQxDe6HJIYyF/9ApnBlGCgxgqIZtizzE+1ZkgcVCS6ROKRFhBI6MtohX2uWn63SL7vAiOZMkpGQnZh0Vzp5dPg4bqN5KbaKyIoo0wZExtHSQ/chFamsYlEAHMBaNhS1VUC5gedFOgwcSBGd++mr1v++pIJ9qWmhlCXwZ1TsPRjMxaAivCnyubfWosfZOSNIuCFe6mEm/DCE6hc0AWqn6w95sH1I=
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: X9z3sxI4QyfU92R1kGQxZdzzSqkx7nRrJp8L/lSXsYdRAr66E2q+xjiFj5BoF3KXxTOFVP1R2dr1U/dbg0xMXTLjwepWavcy8l14z2fpP5YYES68ht1i+TBcblvQsrAOxoyx7ucXNy55cq/+9R6QdQKuimIGG19JmjLLEooYeqGlC2gj8Qxcc9VDsWmECmVebIbBxwC4uewO7LuzIhsM0WRh+d6l5ZUbUHqdrjDYlLXykj83w+Chx9i2GTRVwC32Zm8hYo/pXmlaE2rLg+2CK+GQCV5iv8y6yA7VP4ZihCyXh9oAxkIAqoQl6BqaPXfBOhVZXiPm9y4zRfc4bJff3Wl3KLdQwAiJDdgm7jE/VKiy9NzRGOTLTGaSTeVbapXgZeAOlcUOdDVmpXrJxV4OJlDdLEDlz9dYKV8FeOKlc3fRJOA0cvtpGRkMte/8AWl++9hpcJ5fK5086DVDo3tUDw/vyfO50GwcHpO1/c/+RKHSTR5fddpLvnQDUitPztIAGdJRlpbzsXcEupbYYqtu1m2V3D+ZOEfDKniRguDKd8gLsbJyC/OweoIHjIAvJUYkLkYN73fzMemisdbyPDSMri4PnocPe3StFVRdzNL0kzoXmdE/8fhOfOv3hK4UQvTmWN5qnTbPqDMfWk1ZFWdDSO+o+wi4MdXCQa1fLXncJKU=
    - # ^^ GPG_KEY_NAME
    - secure: TWycCGAWvL45h2YN6I0KEXP5fYFCv65UTEft34bDh2YZqACa0UrndKGexNl0+33v+7ldZdm+MXqMLal3yql9PPuSO5QnjIcL+qwptk679+xYm4t5susHim2G1bBXj6SM9LGLsgk/P5x0y0VA8SO2rioy4cvrzQXWBvioD+e2G4s/nNMZQAI+PH5geQvchsNylFFhDVD4bqoASjtnQMz/NMK0hPA0ecsB8wGLvQWOSho/Med9ZqaqEL+ConoXAkLiRIlIRbtaYKRGPACYWNmSLp1+64PT57Gs2Y/YMT/Id+reqmPm8zav4Q3l1sjPYloP9R3ZgX2fK9X4M9ONa8RJejSc4tj0QfCCg5PWnLy1HUcAzIqMKo0V2+wqmmMCOZf8zxQtjUvvfY15Qz5l+RQrYHBuhaF2o9i9+eGoQ6dCsGSJAFE9fx94AicWs/xFulYvMDWbhMYE85ss5pxrs5QMiUWiZ2NiYCCMjJlEcFWq0FS8JWc9vIUIAgQSyIgiHVV6pCVrxwUpo+MLvOtyudPYsV0agEZpkltM9at4NHRFlXWW2cdLOtqnaSHGP+3ylWk3lMZgdp4WgNMixgCEee7WsvkPcyiEnQGM2jQ1OdZ1+ZFv+HrNeiwscobblvLCIQCgm6NUxeuuCMaaopVfOztrLdW7Gmwv89UrYfY40lFQ/5M=
    - # ^^ GPG_PASSPHRASE
    - secure: J5ql4cChNVE8usEvALUpZf1SObMZbyZwhXCoU9dXqsdhy0XdwuKuQZcNuasKzoERF5cbWTPVNQrbQaBXceTi6lQKOIWEPeYLaxk7ON7eKVkNMERX03mbB86+Pre1Ci8f9p6yd427+auzSK8FjPi37MtE8lAFj34/PQPn0lSXWyxAyj3XxHTohVt/ExK/NrQLLIOZr1Y8MMesdb9rBkS+LClSx5av05uJnI+hWzk38B23QUY10K7zstUpDDkzngo4Cl0lBjt1lNwGnZsbkqZS1dG50tyGWCnsML8iIaRCc2acw41DrX4JE8PZl303G4KIei7O8mD64xJCjZvqrSBL861rkmfiHFwoqWrCFgmwf3YfO52+GheBWAdoEr4eJ0bS92oXr397THrHHXvxgjMlxi5j6OWMK8K807klSOAFNy4MM3mwagkJtIwhVYnrawmMZxolimNtMciUypB5SYv7YBr1lY9CWB6SMyQu1JO4Q8RjK+UJ94SzOUNzFkTmW6NGZvbKw32Y7PvUgSArdLadyUbsX50N3/KluWsSqVpC/g/ReXhmoy4KXPan19eHfhXOgWQpanP3ienofdlKjGaC+wxzLjeUljXmS2hDCv/aw6ha64KmEgGoQ55ly20aEEGH9KXHflBDAlYAnotx8YeodgdmLQ3fHgi4O4IsTVfcy+0=

install: mvn install -P !release -Dmaven.javadoc.skip=true -B -V -f chao/pom.xml

deploy:
  skip_cleanup: true

script:
  - chmod +x chao/before-deploy.sh
  - chmod +x chao/deploy.sh

after_success:
  - cd chao
  - before-deploy.sh
  - deploy.sh
  
cache:
  directories:
    - ~/.m2/repository